index:
   path: /
   controller: App\Controller\Admin\DashboardController::index
api_login_check:
    path: /api/login_check
# config/routes.yaml
gesdinet_jwt_refresh_token:
    path:       /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh    
